# Site settings
title: Raphael Silva
description: 'Make your choice, adventurous Stranger, <br />
              strike the bell and bide the danger, <br />
              or wonder til it drives you mad <br />
              what would have followed if you had. <br />
              - C. S. Lewis'
url: 'http://peagasilva.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Raphael Silva'
  email: sr.silvaraphael@gmail.com
  twitter_username: peagasilva
  facebook_username: sr.silvaraphael
  github_username: peagasilva
  linkedin_username: raphaelaugustosilva
  stackoverflow_username: users/3228888/raphael-silva

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
